import "@/styles/reset.css";
import "@/styles/global.css";
import "@/styles/variable.css";

import Footer from "@/components/footer";
import Header from "@/components/header";

import { Poppins } from "next/font/google";

const popFont = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Ayxan Mustafayev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={popFont.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
